### ISSUE TITLE
Error Log after using /login command

### ISSUE THREAD

**Issue by JStein01** [lachylegend/Moodle-Discord-Buddy#1]
Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/home/ubuntu/Moodle-Discord-Buddy/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:265:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext._evaluateInternal (/home/ubuntu/Moodle-Discord-Buddy/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:219:60)
    at async ExecutionContext.evaluate (/home/ubuntu/Moodle-Discord-Buddy/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Object.LoginToMoodle (/home/ubuntu/Moodle-Discord-Buddy/util/functions.js:100:24)
    at async Object.run (/home/ubuntu/Moodle-Discord-Buddy/slashcommands/loginslash.js:55:9)
    at async Client.<anonymous> (/home/ubuntu/Moodle-Discord-Buddy/index.js:113:5)
Uncaught Promise Exception (Monitor):
 RangeError [MessageContentType]: Message content must be a string.
    at verifyString (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/util/Util.js:426:39)
    at MessagePayload.makeContent (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/structures/MessagePayload.js:111:17)
    at MessagePayload.resolveBody (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/structures/MessagePayload.js:126:26)
    at InteractionWebhook.editMessage (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/structures/Webhook.js:336:50)
    at ChatInputCommandInteraction.editReply (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:158:36)
    at /home/ubuntu/Moodle-Discord-Buddy/slashcommands/loginslash.js:75:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (/home/ubuntu/Moodle-Discord-Buddy/slashcommands/loginslash.js:55:9)
    at async Client.<anonymous> (/home/ubuntu/Moodle-Discord-Buddy/index.js:113:5) {
  code: 'MessageContentType'
} RangeError [MessageContentType]: Message content must be a string.
Uncaught Promise Exception:
 RangeError [MessageContentType]: Message content must be a string.
    at verifyString (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/util/Util.js:426:39)
    at MessagePayload.makeContent (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/structures/MessagePayload.js:111:17)
    at MessagePayload.resolveBody (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/structures/MessagePayload.js:126:26)
    at InteractionWebhook.editMessage (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/structures/Webhook.js:336:50)
    at ChatInputCommandInteraction.editReply (/home/ubuntu/Moodle-Discord-Buddy/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:158:36)
    at /home/ubuntu/Moodle-Discord-Buddy/slashcommands/loginslash.js:75:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (/home/ubuntu/Moodle-Discord-Buddy/slashcommands/loginslash.js:55:9)
    at async Client.<anonymous> (/home/ubuntu/Moodle-Discord-Buddy/index.js:113:5) {
  code: 'MessageContentType'
}

**Comment by 0xLachy** [comment]
damnit that's so annoying, yep I'll try fix that soon, I see the issue
